version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Puerto expuesto para la API
      - "5001:5001" # HTTPS, si aplica
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mariaDB;Database=clientes;User=;Password=!
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin:latest
    ports: 
      - 8080:80    
    environment:
      PMA_HOST: localhost:3306
      PMA_USER: user
      PMA_PASSWORD: 1234
    restart: unless-stopped
    depends_on:
       - db
  db:
    image: mariadb :10.6
    container_name: mariadb
    ports:
      - "3306:3306" # Puerto de SQL Server
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: 1234
      MARIADB_DATABASE: clientes 
      MARIADB_ROOT_PASSWORD: 1234
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
  